### ISSUE TITLE
readmeai.factory.ReadFileException: Exception: failed to read file conf/conf.toml: [Errno 2] No such file or directory: 'conf/conf.toml'

### ISSUE THREAD

**Issue by copbrick** [eli64s/readme-ai#41]
Getting this when trying to run the generate readme command

**Comment by eli64s** [comment]
Fix #41: Add the following line to the [pyproject.toml](https://github.com/eli64s/readme-ai/blob/main/pyproject.toml):

```toml
[tool.poetry.package]
include = ["conf/*.toml"]
```

Commit: 5ce4a0a
